# Welcome to Jekyll!
#
title: bryce thuilot
email: bryce@thuilot.io
description: >- 
    cs student @ Northeastern
baseurl: "" 
url: "thuilot.io" 

permalink: /:title
blog_url: /blog

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
