# Welcome to Jekyll!
#
title: bryce thuilot
email: bryce@thuilot.io
description: >- 
    application security @ Blackstone
baseurl: "" 
url: "thuilot.io" 

permalink: /:title
blog_url: /blog

google_analytics: G-6P09F1Z9CV

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag

kramdown:
  input: GFM

